from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 365)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(-21, -11, 261, 471))
        self.frame_2.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(60, 20, 131, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 30pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 121, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(50, 130, 181, 17))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 160, 171, 17))
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 190, 161, 17))
        self.checkBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(50, 220, 171, 17))
        self.checkBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(310, 60, 160, 124))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_2.setMinimum(7000)
        self.spinBox_2.setMaximum(20000)
        self.spinBox_2.setSingleStep(1000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox.setMaximum(60)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.spinBox_3 = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_3.setMaximum(89)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox_4.setMaximum(300)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_4)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(340, 30, 101, 21))
        self.label_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(80, 270, 75, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_5.setGeometry(QtCore.QRect(310, 190, 161, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(310, 250, 160, 81))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_8 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_8.setMaximum(300)
        self.spinBox_8.setObjectName("spinBox_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_8)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBox_7 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_7.setMaximum(89)
        self.spinBox_7.setObjectName("spinBox_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_7)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spinBox_6 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_6.setMaximum(60)
        self.spinBox_6.setObjectName("spinBox_6")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_6)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(310, 220, 161, 21))
        self.label_14.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lock-in Simulador"))
        self.label.setText(_translate("MainWindow", "Lock-in"))
        self.label_2.setText(_translate("MainWindow", "Simulador"))
        self.checkBox.setText(_translate("MainWindow", "Plotar Sinal de Entrada"))
        self.checkBox_2.setText(_translate("MainWindow", "Plotar Sinal Referência"))
        self.checkBox_3.setText(_translate("MainWindow", "Plotar Sinais Multiplicados"))
        self.checkBox_4.setText(_translate("MainWindow", "Plotar Sinais Passa-Baixo"))
        self.label_6.setText(_translate("MainWindow", "Amplitude:"))
        self.label_7.setText(_translate("MainWindow", "Fase:"))
        self.label_8.setText(_translate("MainWindow", "Frequência:"))
        self.label_9.setText(_translate("MainWindow", "Nº Pontos:"))
        self.label_10.setText(_translate("MainWindow", "Sinal Entrada"))
        self.pushButton.setText(_translate("MainWindow", "INICIAR"))
        self.checkBox_5.setText(_translate("MainWindow", "Simular dois Sinais de Entrada"))
        self.label_11.setText(_translate("MainWindow", "Amplitude:"))
        self.label_12.setText(_translate("MainWindow", "Fase:"))
        self.label_13.setText(_translate("MainWindow", "Frequência:"))
        self.label_14.setText(_translate("MainWindow", "Segundo Sinal Entrada"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
